# Generated by Django 5.2 on 2025-06-17 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0003_alter_article_language_delete_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='File')),
                ('name', models.CharField(blank=True, max_length=100)),
                (
                    'article',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='articles.article'
                    ),
                ),
            ],
        ),
    ]
