# Generated by Django 5.2 on 2025-11-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
