# Generated by Django 5.2 on 2025-06-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_content_alter_article_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(
                choices=[('en', 'English'), ('ru', 'Russian'), ('it', 'Italian'), ('sl', 'Slovenian')],
                default='en',
                max_length=2,
            ),
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
